; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Hack-Pack-Installer"
#define MyAppVersion "1.02"
#define MyAppPublisher "JoshuaMK"
#define MyAppExeName "Installer.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CBE8AEB8-67A1-48A2-B14C-3132E93B34A5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\HackPackInstaller
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Users\10gra\Documents\Hack Pack Python\InnoOutput
OutputBaseFilename=InstallerSetup
SetupIconFile=C:\Users\10gra\Documents\Hack Pack Python\hack_pack.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\10gra\Documents\Hack Pack Python\Installer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\10gra\Documents\Hack Pack Python\Updater.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\10gra\Documents\Hack Pack Python\telephone.wav"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\10gra\Documents\Hack Pack Python\version.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\10gra\Documents\Hack Pack Python\config.ini"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

